name: "Performance comparison"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to compare with default branch (master)"
        required: true
        default: ""
        type: string
      bench_master_cache_key:
        description: "Cache key for default branch benchmark result"
        required: false
        default: "benchmark-master"
        type: string
  workflow_call:
    inputs:
      bench_master_cache_key:
        description: "Cache key for default branch benchmark result"
        required: false
        default: "benchmark-master"
        type: string

env:
  GIT_CONFIG_GLOBAL: "/root/.gitconfig" # fix path in container (https://github.com/actions/runner/issues/2033)
  CHECKOUT_BRANCH: "${{ (inputs.branch != '' && inputs.branch) || github.head_ref }}"

jobs:
  compare:
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/tarantool/sdvg-ci:0.0.2"

    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "${{ env.CHECKOUT_BRANCH }}"

      - name: "Try fetch cached benchmark result from master branch"
        id: "cache-benchmark"
        uses: "actions/cache/restore@v4"
        with:
          key: "${{ inputs.bench_master_cache_key }}"
          path: "benchmark-master.txt"

      - name: "Fetch master branch"
        if: ${{ steps.cache-benchmark.outputs.cache-hit != 'true' }}
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: "master_branch"

      - name: "Create master benchmark"
        if: ${{ steps.cache-benchmark.outputs.cache-hit != 'true' }}
        working-directory: "master_branch"
        run: make test/performance > ../benchmark-master.txt

      - name: "Update cache with benchmark-master.txt"
        if: ${{ steps.cache-benchmark.outputs.cache-hit != 'true' }}
        uses: "actions/cache/save@v4"
        with:
          key: "${{ inputs.bench_master_cache_key }}"
          path: "benchmark-master.txt"

      - name: "Run benchmarks on PR branch"
        run: make test/performance > benchmark-pr.txt

      - name: "Get comparison results"
        run: |
          echo -e \
            "# Perf tests comparison: \`${{ github.event.repository.default_branch }}\` VS \`${{ github.head_ref }}\`\n" \
            > performance-report.md
          python ./build/ci/compare_benchmarks.py \
            benchmark-master.txt benchmark-pr.txt \
            --alert-threshold 7 \
            --aggregation mean \
            >> performance-report.md
          cat performance-report.md >> $GITHUB_STEP_SUMMARY

      - uses: "mshick/add-pr-comment@v2"
        if: ${{ github.event_name == 'pull_request' }}
        with:
          message-path: "performance-report.md"
          message-id: "perf-report-pr-${{ github.event.pull_request.number }}"
          refresh-message-position: true
